name: webapp-deploy

on:
  push:
    branches:
      - master
      - development

jobs:
  webapp-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build project
        run: |
          cd web-app
          npm ci
          npm run build

      - name: Set to live if branch is master
        if: github.ref == 'refs/heads/master'
        run: |
          cd web-app
          contents="$(jq '.hosting.site = "charge-hub"' firebase.json)" && \
          echo "${contents}" > firebase.json

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "web-app"
